spring:
  datasource:
    #mysql的连接信息
    url: jdbc:mysql://127.0.0.1:3306/hearttoheart?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone = GMT
    #用户名
    username: wudongyu
    #密码
    password: qqa222888
#  是否打开swagger文档 生产环境关闭
enable:
  swagger: true

